### ISSUE TITLE
Genfit 2 (54c53d9) does not build on Ubuntu 16.04

### ISSUE THREAD

**Issue by pbielefeldt** [GenFit/GenFit#44] opened 2017-03-09 20:11 UTC
Hi!  

I currently try to install Genfit on Ubuntu 16.04 xenial, x86_64 Linux 4.4.0-64-generic. I have cmake 3.5.1, ROOT 5.34/30 and ibboost-dev 1.58.0.1ubuntu1 installed and follow the README instructions.

Here's what I get:
`cmake .. ` 
[...]  
```-- Build files have been written to...  ```

```
make
[ 14%] Building CXX object CMakeFiles/genfit2.dir/GBLRootDict.cc.o
In file included from /home/bielefeldt/genfit2/GBL/include/GFGbl.h:34:0,
                 from /home/bielefeldt/genfit2/build/GBLRootDict.h:34,
                 from /home/bielefeldt/genfit2/build/GBLRootDict.cc:17:
/usr/include/c++/5/sstream:300:7: error: ‘struct std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::__xfer_bufptrs’ redeclared with different access
       struct __xfer_bufptrs
       ^
CMakeFiles/genfit2.dir/build.make:236: recipe for target 'CMakeFiles/genfit2.dir/GBLRootDict.cc.o' failed
make[2]: *** [CMakeFiles/genfit2.dir/GBLRootDict.cc.o] Error 1
CMakeFiles/Makefile2:387: recipe for target 'CMakeFiles/genfit2.dir/all' failed
make[1]: *** [CMakeFiles/genfit2.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
Is there anything I do incorrectly? Iirc, I installed Genfit the same way recently, and it worked (might have been Ubuntu 16.10, I can't check this unfortunately).  

BTW: /build/GBLRootDict.cc:17 is
`#include "GBLRootDict.h"`  

Thanks for any replies!

**Update**
I checked on the other machine … It's Ubuntu 16.04, too, but I had the check-out from the svn. The git repo doesn't compile here, too (same error). Anyone knows why?

**Comment by MarkusPrim** [comment] 2017-03-29 10:32
I was able to check out GenFit and compile it on Ubuntu 16.04 xenial x86_64 4.4.0-70-generic. 
* GenFit should not have a dependency on boost any more.
* I used 
   * ROOT 6.07/07  
   * CMake 3.5.1

So I guess the problem is the ROOT version. Do you have any updates on this issue? Otherwise I will downgrade and further investigate.

**Comment by pbielefeldt** [comment] 2017-03-29 10:37
I just tried again, on another, yet identically configured (I think) machine. Same issue here. My ROOT version is 5.34/30.
BTW: I also tried openSUSE Leap 42.2, ROOT is on 5.34/36 right now, and no issue occurred.

**Comment by MarkusPrim** [comment] 2017-04-04 10:32
I was able to build with ROOT 5.34/36 on Ubuntu 16.04 xenial x86_64. I used CMake 3.5.1 and gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609.

**Comment by MarkusPrim** [comment] 2017-04-20 14:01
I'll close this for the time being. If you have further question please reopen the issue.

**Closed by MarkusPrim** 2017-04-20 14:01 UTC
